on:
    push:
      branches:
        - main
  
jobs:
    build-and-push-for-beta:
      name: Build & Push Docker Image for Production Environment
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.PRODUCTION_AWS_REGION }}
  
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
  
        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.PRODUCTION_AWS_ECR_REPOSITORY_NAME }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build --build-arg APPLICATION_VERSION="${{ github.sha }}" \
            --build-arg NEXT_PUBLIC_API_BASE_URL=${{ secrets.PRODUCTION_NEXT_PUBLIC_API_BASE_URL }} \
            --build-arg NEXT_PUBLIC_API_TRANS_URL=${{ secrets.PRODUCTION_NEXT_PUBLIC_API_TRANS_URL }} \
            --build-arg NEXT_PUBLIC_API_PROMOTION_URL=${{ secrets.PRODUCTION_NEXT_PUBLIC_API_PROMOTION_URL }} \
            --build-arg NEXT_PUBLIC_ODIN_URL=${{ secrets.PRODUCTION_NEXT_PUBLIC_ODIN_URL }} \
            --build-arg NEXT_PUBLIC_CAMOPAY_URL=${{ secrets.PRODUCTION_NEXT_PUBLIC_CAMOPAY_URL }} \
            --build-arg NEXT_PUBLIC_CAMOPAY_KEY=${{ secrets.PRODUCTION_NEXT_PUBLIC_CAMOPAY_KEY }} \
            --build-arg NEXT_PUBLIC_BETBY_BRAND_ID=${{ secrets.PRODUCTION_NEXT_PUBLIC_BETBY_BRAND_ID }} \
            --build-arg NEXT_PUBLIC_BETBY_SCRIPT_URL=${{ secrets.PRODUCTION_NEXT_PUBLIC_BETBY_SCRIPT_URL }} \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
            docker push $REGISTRY/$REPOSITORY:latest
